Dodaj obsługe motywów oraz komponent "Pole tekstowe"
al-mi-pio/alpimi-planner-frontend pull request #15
Opened 2024-12-02 23:16 UTC by ThePanToster

Sprawdzić:
- czy nazwy i struktura plików ma sens
- czy brakuje jakiś unit testów
- w storybooku wszystkie najważniejsze kwestie ( accessibility, wygląd w trybie ciemnym i jasnym, wszystkie warianty komponentu itd. )

2024-12-02 23:56 UTC, piotr102k requested changes
fajna lektura

2024-12-02 23:56 UTC, piotr102k commented on .github/workflows/deploy.yml
> +    NODE_VERSION: '20.16.0'
czy ten tab jest niezbędny?

2024-12-02 23:56 UTC, piotr102k commented on .github/workflows/develop.yml
> +    NODE_VERSION: '20.16.0'
tak samo

2024-12-02 23:59 UTC, ThePanToster commented on .github/workflows/deploy.yml
> +    NODE_VERSION: '20.16.0'
Bez taba było niezgodne z linterem, dodał się automatycznie po uruchomieniu skryptu do formatowania plików w projekcie

2024-12-02 23:59 UTC, ThePanToster commented on .github/workflows/develop.yml
> +    NODE_VERSION: '20.16.0'
Tak samo

2024-12-03 00:03 UTC, piotr102k approved these changes

2024-12-03 00:03 UTC, merged